name = "universe-engine"
main = "workers/api.ts"
compatibility_date = "2025-06-16"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "universe-engine-db"
database_id = "0aebd7a0-0552-4a20-b37d-e9e114dd0308"

[[routes]]
pattern = "api.universemakers.org/*"
zone_id = "5f54973f01c7dd018e6444970213e363"
